```{r}
k<-data.frame(
  Pituus=c(183,160,196,186,195,182,208,169,166,198,145,168),
  Palkka=c(100,92,106,92,109,101,116,96,94,101,93,96)
)
fit<-lm(formula=Palkka~Pituus, data=k)
summary(fit)
anova(fit)
coefficients(fit)[1] + coefficients(fit)[2] * 179
plot(k$Pituus, k$Palkka, col='red', pch=16)
abline(fit)
```
```{r}
beta<-sum(((k$Pituus - mean(k$Pituus)) * (k$Palkka - mean(k$Palkka)))) / sum(((k$Pituus - mean(k$Pituus)))^2)
beta
alpha<-mean(k$Palkka) - beta * mean(k$Pituus)
alpha
```
```{r}
S_XY<-sum(k$Pituus * k$Palkka) - sum(nrow(k) * mean(k$Pituus) * mean(k$Palkka))
S_XX<-sum(k$Pituus^2) - sum(nrow(k) * mean(k$Pituus)^2)
S_YY<-sum(k$Palkka^2) - sum(nrow(k) * mean(k$Palkka)^2)
SS_R<-sum((k$Palkka - alpha - beta * k$Pituus)^2)
var_est<-((S_XX * S_YY - S_XY^2) / S_XX) / (nrow(k) - 2)
var_est
```
```{r}
cof<-data.frame(
  paino=c(60,79,102,67,65,87,55,96,81),
  pituus=c(168,175,189,159,165,191,156,201,180),
  kahvi=c(1,18,0,10,2,3,0,2,9)
)
beta<-sum((cof$paino - mean(cof$paino)) * (cof$pituus - mean(cof$paino))) / sum((cof$paino - mean(cof$paino))^2)
alpha<-mean(cof$pituus) - beta * mean(cof$paino)

fit=lm(pituus~paino, cof)
S_XY<-sum(cof$paino * cof$pituus) - sum(nrow(cof) * mean(cof$paino) * mean(cof$pituus))
S_XX<-sum(cof$paino^2) - sum(nrow(cof) * mean(cof$paino)^2)
S_YY<-sum(cof$pituus^2) - sum(nrow(cof) * mean(cof$pituus)^2)
SS_R<-sum((cof$pituus - alpha - beta * cof$paino)^2)
var_est<-((S_XX * S_YY - S_XY^2) / S_XX) / (nrow(cof) - 2)

ts<-sqrt(((nrow(cof) - 2)*S_XX)/SS_R) * beta
2*pt(ts, nrow(cof) - 2, lower.tail=FALSE)
```
```{r}
beta<-sum((cof$paino - mean(cof$paino)) * (cof$kahvi - mean(cof$kahvi))) / sum((cof$paino - mean(cof$paino))^2)
alpha<-mean(cof$kahvi) - beta * mean(cof$paino)

S_XY<-sum(cof$paino * cof$kahvi) - sum(nrow(cof) * mean(cof$paino) * mean(cof$kahvi))
S_XX<-sum(cof$paino^2) - sum(nrow(cof) * mean(cof$paino)^2)
S_YY<-sum(cof$kahvi^2) - sum(nrow(cof) * mean(cof$kahvi)^2)
SS_R<-sum((cof$kahvi - alpha - beta * cof$paino)^2)
var_est<-((S_XX * S_YY - S_XY^2) / S_XX) / (nrow(cof) - 2)

ts<-sqrt(((nrow(cof) - 2)*S_XX)/SS_R) * beta
2*pt(ts, nrow(cof) - 2, lower.tail=FALSE)
```
```{r}
pr=data.frame(
  vankilassa=c(18.63,9.9,2.83,4.73,17.8,2.34,9.92,1.81,0.42,20.86,1.05,5.44),
  ehdonalaisessa=c(11.42,2.8,1.97,2.28,6.64,1.36,4.53,0.36,0.17,6.51,0.42,3.85)
)

fit=lm(ehdonalaisessa~vankilassa, data=pr)
plot(pr$vankilassa, pr$ehdonalaisessa, col='red', pch=16)
par(new=TRUE)
plot(data.frame(
      vankilassa=c(14.5, 18.22),
      ehdonalaisessa=c(predict(fit, newdata=data.frame(vankilassa=c(14.5, 18.22))))
      ),
     col='gray',
     pch=16
)
abline(fit)
predict(fit, newdata=data.frame(vankilassa=c(14.5, 18.22)))
```

